#ifndef MEMPRESS_VERSION_H
#define MEMPRESS_VERSION_H

#define MEMPRESS_VERSION_STRINGIZE_IMPL(value) #value
#define MEMPRESS_VERSION_STRINGIZE(value) MEMPRESS_VERSION_STRINGIZE_IMPL(value)
#define MEMPRESS_VERSION_WIDE_STRINGIZE_IMPL(value) L#value
#define MEMPRESS_VERSION_WIDE_STRINGIZE(value) MEMPRESS_VERSION_WIDE_STRINGIZE_IMPL(value)

#endif
